export const data = {
	number: '1',
	name: 'Bagarić Ivan',
	middleName: 'nema',
	sex: 'm',
	parent: 'nema',
	birth: 'nema',
	death: 'nema',
	place: 'Tomislavgrad',
	country: 'BiH',
	children: [
		{
			number: '2',
			name: 'Bagarić Križan',
			middleName: 'nema',
			sex: 'm',
			parent: 'Ivan',
			birth: 'nema',
			death: 'nema',
			place: 'Tomislavgrad',
			country: 'BiH',
			children: [
				{
					number: '3',
					name: 'Petrović Stojan',
					middleName: 'nema',
					sex: 'm',
					parent: 'Križan',
					birth: '1862',
					death: '1942',
					place: 'Tomislavgrad',
					country: 'BiH',
					children: [
						{
							number: '4',
							name: 'Pokrajčić Delfa',
							middleName: 'nema',
							sex: 'ž',
							parent: 'Stojan',
							birth: '1893',
							death: 'nema',
							place: 'Tomislavgrad',
							country: 'BiH',
						},
						{
							number: '4',
							name: 'Petrović Stjepan',
							middleName: 'Stipica',
							sex: 'm',
							parent: 'Stojan',
							birth: '1897',
							death: '1954',
							place: 'Tomislavgrad',
							country: 'BiH',
							children: [
								{
									number: '5',
									name: 'Petrović Jozo',
									middleName: 'nema',
									sex: 'm',
									parent: 'Stjepan Stipica',
									birth: '1925',
									death: '2004',
									place: 'Tomislavgrad',
									country: 'BiH',
									children: [
										{
											number: '6',
											name: 'Petrović Dominik',
											middleName: 'Domin',
											sex: 'm',
											parent: 'Jozo',
											birth: '1954',
											death: 'nema',
											place: 'Tomislavgrad',
											country: 'BiH',
											children: [
												{
													number: '7',
													name: 'Petrović Josip',
													middleName: 'Buco',
													sex: 'm',
													parent: 'Dominik Domin',
													birth: '1985',
													death: 'nema',
													place: 'Čapljina',
													country: 'BiH',
													children: [
														{
															number: '8',
															name: 'Petrović Vinka',
															middleName: 'nema',
															sex: 'ž',
															parent: 'Josip Buco',
															birth: '2015',
															death: 'nema',
															place: 'Čapljina',
															country: 'BiH',
														},
														{
															number: '8',
															name: 'Petrović Dominik',
															middleName: 'nema',
															sex: 'm',
															parent: 'Josip Buco',
															birth: '2016',
															death: 'nema',
															place: 'Čapljina',
															country: 'BiH',
														},
														{
															number: '8',
															name: 'Petrović Mihael',
															middleName: 'nema',
															sex: 'm',
															parent: 'Josip Buco',
															birth: '2018',
															death: 'nema',
															place: 'Čapljina',
															country: 'BiH',
														},
													],
												},
												{
													number: '7',
													name: 'Petrović Ilija',
													middleName: 'nema',
													sex: 'm',
													parent: 'Dominik Domin',
													birth: '1988',
													death: 'nema',
													place: 'Graz',
													country: 'Austrija',
													children: [
														{
															number: '8',
															name: 'Petrović Lucija',
															middleName: 'nema',
															sex: 'ž',
															parent: 'Ilija',
															birth: '2017',
															death: 'nema',
															place: 'Graz',
															country: 'Austrija',
														},
														{
															number: '8',
															name: 'Petrović Magdalena',
															middleName: 'nema',
															sex: 'ž',
															parent: 'Ilija',
															birth: '2019',
															death: 'nema',
															place: 'Graz',
															country: 'Austrija',
														},
														{
															number: '8',
															name: 'Petrović Gabrijel',
															middleName: 'nema',
															sex: 'm',
															parent: 'Ilija',
															birth: '2022',
															death: 'nema',
															place: 'Graz',
															country: 'Austrija',
														},
													],
												},
												{
													number: '7',
													name: 'Petrović Stjepan',
													middleName: 'nema',
													sex: 'm',
													parent: 'Dominik Domin',
													birth: '1990',
													death: 'nema',
													place: 'Leoben',
													country: 'Austrija',
													children: [
														{
															number: '8',
															name: 'Petrović Mia',
															middleName: 'nema',
															sex: 'ž',
															parent: 'Stjepan',
															birth: '2016',
															death: 'nema',
															place: 'Leoben',
															country: 'Austrija',
														},
														{
															number: '8',
															name: 'Petrović Katarina',
															middleName: 'nema',
															sex: 'ž',
															parent: 'Stjepan',
															birth: '2020',
															death: 'nema',
															place: 'Leoben',
															country: 'Austrija',
														},
													],
												},
												{
													number: '7',
													name: 'Skočibušić Ruža',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Dominik Domin',
													birth: '1994',
													death: 'nema',
													place: 'Graz',
													country: 'Austrija',
													children: [
														{
															number: '8',
															name: 'Skočibušić Ante',
															middleName: 'nema',
															sex: 'm',
															parent: 'Ruža',
															birth: '2022',
															death: 'nema',
															place: 'Graz',
															country: 'Austrija',
														},
													],
												},
											],
										},
										{
											number: '6',
											name: 'Jurič Matija',
											middleName: 'nema',
											sex: 'ž',
											parent: 'Jozo',
											birth: '1956',
											death: 'nema',
											place: 'Tomislavgrad',
											country: 'BiH',
											children: [
												{
													number: '7',
													name: 'Škalic Mladenka',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Matija',
													birth: '1977',
													death: 'nema',
													place: 'Rodgau',
													country: 'Njemačka',
													children: [
														{
															number: '8',
															name: 'Škalić Matea',
															middleName: 'nema',
															sex: 'ž',
															parent: 'Mladenka',
															birth: '2002',
															death: 'nema',
															place: 'Rodgau',
															country: 'Njemačka',
														},
													],
												},
												{
													number: '7',
													name: 'Bačić Danijela',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Matija',
													birth: '1981',
													death: 'nema',
													place: 'Obertshausen',
													country: 'Njemačka',
													children: [
														{
															number: '8',
															name: 'Bačić Mateo',
															middleName: 'nema',
															sex: 'm',
															parent: 'Danijela',
															birth: '2018',
															death: 'nema',
															place: 'Obertshausen',
															country: 'Njemačka',
														},
														{
															number: '8',
															name: 'Bačić Niko-Filip',
															middleName: 'nema',
															sex: 'm',
															parent: 'Danijela',
															birth: '2021',
															death: 'nema',
															place: 'Obertshausen',
															country: 'Njemačka',
														},
													],
												},
												{
													number: '7',
													name: 'Jurič Tina',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Matija',
													birth: '1983',
													death: 'nema',
													place: 'Rodgau',
													country: 'Njemačka',
												},
											],
										},
									],
								},
								{
									number: '6',
									name: 'Čamber Gina',
									middleName: 'nema',
									sex: 'ž',
									parent: 'Jozo',
									birth: '1958',
									death: 'nema',
									place: 'Posušje',
									country: 'BiH',
									children: [
										{
											number: '7',
											name: 'Jukić Ljubica',
											middleName: 'nema',
											sex: 'ž',
											parent: 'Gina',
											birth: '1983',
											death: 'nema',
											place: 'Posušje',
											country: 'BiH',
											children: [
												{
													number: '8',
													name: 'Jukić Petra',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Ljubica',
													birth: '2012',
													death: 'nema',
													place: 'Posušje',
													country: 'BiH',
												},
												{
													number: '8',
													name: 'Jukić Zvonko',
													middleName: 'nema',
													sex: 'm',
													parent: 'Ljubica',
													birth: '2014',
													death: 'nema',
													place: 'Posušje',
													country: 'BiH',
												},
												{
													number: '8',
													name: 'Jukić Filipa',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Ljubica',
													birth: '2019',
													death: 'nema',
													place: 'Posušje',
													country: 'BiH',
												},
											],
										},
										{
											number: '7',
											name: 'Gabelica Ružica',
											middleName: 'nema',
											sex: 'ž',
											parent: 'Gina',
											birth: '1986',
											death: 'nema',
											place: 'Podbablje Gornje',
											country: 'Hrvatska',
											children: [
												{
													number: '8',
													name: 'Gabelica Marko',
													middleName: 'nema',
													sex: 'm',
													parent: 'Ružica',
													birth: '2012',
													death: 'nema',
													place: 'Podbablje Gornje',
													country: 'Hrvatska',
												},
												{
													number: '8',
													name: 'Gabelica Marijan',
													middleName: 'nema',
													sex: 'm',
													parent: 'Ružica',
													birth: '2016',
													death: 'nema',
													place: 'Podbablje Gornje',
													country: 'Hrvatska',
												},
											],
										},
										{
											number: '7',
											name: 'Čamber Ivan',
											middleName: 'nema',
											sex: 'm',
											parent: 'Gina',
											birth: '1989',
											death: 'nema',
											place: 'Beč',
											country: 'Austrija',
											children: [
												{
													number: '8',
													name: 'Čamber Stipe',
													middleName: 'nema',
													sex: 'm',
													parent: 'Ivan',
													birth: '2021',
													death: 'nema',
													place: 'Beč',
													country: 'Austrija',
												},
											],
										},
										{
											number: '6',
											name: 'Petrović Nedjeljko',
											middleName: 'Nedo',
											sex: 'm',
											parent: 'Jozo',
											birth: '1962',
											death: 'nema',
											place: 'Tomislavgrad',
											country: 'BiH',
											children: [
												{
													number: '7',
													name: 'Stanić Josipa',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Nedjeljko Nedo',
													birth: '1993',
													death: 'nema',
													place: 'Tomislavgrad',
													country: 'BiH',
													children: [
														{
															number: '8',
															name: 'Stanić Ante',
															middleName: 'nema',
															sex: 'm',
															parent: 'Josipa',
															birth: '2021',
															death: 'nema',
															place: 'Tomislavgrad',
															country: 'BiH',
														},
													],
												},
												{
													number: '7',
													name: 'Petrović Mateja',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Nedjeljko Nedo',
													birth: '1995',
													death: 'nema',
													place: 'Tomislavgrad',
													country: 'BiH',
												},
												{
													number: '7',
													name: 'Petrović Marko',
													middleName: 'nema',
													sex: 'm',
													parent: 'Nedjeljko Nedo',
													birth: '2000',
													death: 'nema',
													place: 'Tomislavgrad',
													country: 'BiH',
												},
											],
										},
										{
											number: '6',
											name: 'Petrović Vladimir',
											middleName: 'Vlado',
											sex: 'm',
											parent: 'Jozo',
											birth: '1965',
											death: '2019',
											place: 'Tomislavgrad',
											country: 'BiH',
										},
									],
								},
								{
									number: '5',
									name: 'Petrović Janja',
									middleName: 'nema',
									sex: 'ž',
									parent: 'Stjepan Stipica',
									birth: '1929',
									death: '1980',
									place: 'Tomislavgrad',
									country: 'BiH',
								},
								{
									number: '5',
									name: 'Lončar Zdravka',
									middleName: 'nema',
									sex: 'ž',
									parent: 'Stjepan Stipica',
									birth: '1935',
									death: '2016',
									place: 'Posušje',
									country: 'BiH',
									children: [
										{
											number: '6',
											name: 'Lončar Marin',
											middleName: 'nema',
											sex: 'm',
											parent: 'Zdravka',
											birth: '1968',
											death: 'nema',
											place: 'Posušje',
											country: 'BiH',
										},
										{
											number: '6',
											name: 'Lončar Slavo',
											middleName: 'nema',
											sex: 'm',
											parent: 'Zdravka',
											birth: '1970',
											death: 'nema',
											place: 'Posušje',
											country: 'BiH',
										},
									],
								},
								{
									number: '5',
									name: 'Petrović Jela',
									middleName: 'nema',
									sex: 'ž',
									parent: 'Stjepan Stipica',
									birth: '1938',
									death: '2021',
									place: 'Tomislavgrad',
									country: 'BiH',
									children: [
										{
											number: '6',
											name: 'Pranjić Matilda',
											middleName: 'nema',
											sex: 'ž',
											parent: 'Jela',
											birth: '1970',
											death: 'nema',
											place: 'Tomislavgrad',
											country: 'BiH',
											children: [
												{
													number: '7',
													name: 'Pranjić Igor',
													middleName: 'nema',
													sex: 'm',
													parent: 'Matilda',
													birth: '1991',
													death: 'nema',
													place: 'Tomislavgrad',
													country: 'BiH',
												},
												{
													number: '7',
													name: 'Pranjić Robert',
													middleName: 'nema',
													sex: 'm',
													parent: 'Matilda',
													birth: '1994',
													death: 'nema',
													place: 'Tomislavgrad',
													country: 'BiH',
												},
											],
										},
									],
								},
								{
									number: '5',
									name: 'Grbavac Nedjeljka',
									middleName: 'Neda',
									sex: 'ž',
									parent: 'Stjepan Stipica',
									birth: '1941',
									death: '2007',
									place: 'Ljubuški',
									country: 'BiH',
									children: [
										{
											number: '6',
											name: 'Vukojević Zdenka',
											middleName: 'nema',
											sex: 'ž',
											parent: 'Neda',
											birth: '1962',
											death: 'nema',
											place: 'Ljubuški',
											country: 'BiH',
											children: [
												{
													number: '7',
													name: 'Vukojević Nikola',
													middleName: 'nema',
													sex: 'm',
													parent: 'Zdenka',
													birth: '2005',
													death: 'nema',
													place: 'Ljubuški',
													country: 'BiH',
												},
											],
										},
										{
											number: '6',
											name: 'Grbavac Zdenko',
											middleName: 'Grba',
											sex: 'm',
											parent: 'Neda',
											birth: '1965',
											death: 'nema',
											place: 'Ljubuški',
											country: 'BiH',
											children: [
												{
													number: '7',
													name: 'Lauc Matea',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Zdenko',
													birth: '1992',
													death: 'nema',
													place: 'Ljubuški',
													country: 'BiH',
												},
												{
													number: '7',
													name: 'Grbavac Lucija',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Zdenko',
													birth: '1996',
													death: 'nema',
													place: 'Ljubuški',
													country: 'BiH',
												},
												{
													number: '7',
													name: 'Grbavac Anđela',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Zdenko',
													birth: '1999',
													death: 'nema',
													place: 'Ljubuški',
													country: 'BiH',
												},
											],
										},
										{
											number: '6',
											name: 'Topić Gordana',
											middleName: 'Goga',
											sex: 'ž',
											parent: 'Neda',
											birth: '1970',
											death: 'nema',
											place: 'Zaostrog',
											country: 'Hrvatska',
											children: [
												{
													number: '7',
													name: 'Topić Marina',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Gordana',
													birth: '1991',
													death: 'nema',
													place: 'Zaostrog',
													country: 'Hrvatska',
												},
												{
													number: '7',
													name: 'Topić Josipa',
													middleName: 'nema',
													sex: 'ž',
													parent: 'Gordana',
													birth: '1993',
													death: 'nema',
													place: 'Zaostrog',
													country: 'Hrvatska',
												},
											],
										},
									],
								},
							],
						},
					],
				},
			],
		},
	],
};
